/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampusMapRouteImport } from './routes/campus-map'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingsIdRouteImport } from './routes/buildings.$id'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusMapRoute = CampusMapRouteImport.update({
  id: '/campus-map',
  path: '/campus-map',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsIdRoute = BuildingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuildingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/campus-map': typeof CampusMapRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/buildings/$id': typeof BuildingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/campus-map': typeof CampusMapRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/buildings/$id': typeof BuildingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/campus-map': typeof CampusMapRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/favorites': typeof FavoritesRoute
  '/buildings/$id': typeof BuildingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buildings'
    | '/campus-map'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/favorites'
    | '/buildings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buildings'
    | '/campus-map'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/favorites'
    | '/buildings/$id'
  id:
    | '__root__'
    | '/'
    | '/buildings'
    | '/campus-map'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/favorites'
    | '/buildings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingsRoute: typeof BuildingsRouteWithChildren
  CampusMapRoute: typeof CampusMapRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FavoritesRoute: typeof FavoritesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-map': {
      id: '/campus-map'
      path: '/campus-map'
      fullPath: '/campus-map'
      preLoaderRoute: typeof CampusMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/$id': {
      id: '/buildings/$id'
      path: '/$id'
      fullPath: '/buildings/$id'
      preLoaderRoute: typeof BuildingsIdRouteImport
      parentRoute: typeof BuildingsRoute
    }
  }
}

interface BuildingsRouteChildren {
  BuildingsIdRoute: typeof BuildingsIdRoute
}

const BuildingsRouteChildren: BuildingsRouteChildren = {
  BuildingsIdRoute: BuildingsIdRoute,
}

const BuildingsRouteWithChildren = BuildingsRoute._addFileChildren(
  BuildingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingsRoute: BuildingsRouteWithChildren,
  CampusMapRoute: CampusMapRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  FacilitiesRoute: FacilitiesRoute,
  FavoritesRoute: FavoritesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
